// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.12.4
// source: email-service.proto

package mail_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailServiceRequest) Reset() {
	*x = MailServiceRequest{}
	mi := &file_email_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailServiceRequest) ProtoMessage() {}

func (x *MailServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailServiceRequest.ProtoReflect.Descriptor instead.
func (*MailServiceRequest) Descriptor() ([]byte, []int) {
	return file_email_service_proto_rawDescGZIP(), []int{0}
}

func (x *MailServiceRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MailServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MailServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailServiceResponse) Reset() {
	*x = MailServiceResponse{}
	mi := &file_email_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailServiceResponse) ProtoMessage() {}

func (x *MailServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailServiceResponse.ProtoReflect.Descriptor instead.
func (*MailServiceResponse) Descriptor() ([]byte, []int) {
	return file_email_service_proto_rawDescGZIP(), []int{1}
}

func (x *MailServiceResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_email_service_proto protoreflect.FileDescriptor

var file_email_service_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x12, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x13, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x49, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x4d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_email_service_proto_rawDescOnce sync.Once
	file_email_service_proto_rawDescData []byte
)

func file_email_service_proto_rawDescGZIP() []byte {
	file_email_service_proto_rawDescOnce.Do(func() {
		file_email_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_service_proto_rawDesc), len(file_email_service_proto_rawDesc)))
	})
	return file_email_service_proto_rawDescData
}

var file_email_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_email_service_proto_goTypes = []any{
	(*MailServiceRequest)(nil),  // 0: MailServiceRequest
	(*MailServiceResponse)(nil), // 1: MailServiceResponse
}
var file_email_service_proto_depIdxs = []int32{
	0, // 0: EmailService.EmailService:input_type -> MailServiceRequest
	1, // 1: EmailService.EmailService:output_type -> MailServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_email_service_proto_init() }
func file_email_service_proto_init() {
	if File_email_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_service_proto_rawDesc), len(file_email_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_service_proto_goTypes,
		DependencyIndexes: file_email_service_proto_depIdxs,
		MessageInfos:      file_email_service_proto_msgTypes,
	}.Build()
	File_email_service_proto = out.File
	file_email_service_proto_goTypes = nil
	file_email_service_proto_depIdxs = nil
}
